.TH QAIRCRACK 1 "May 18, 2011"
.SH "NAME"
qaircrack \- Buscador de claves wifi.
.SH "SYNOPSIS"
.B qaircrack
.SH "DESCRIPTION"
Interfaz gráfica en Qt4 para aircrack-ng.
.PP
.B qaircrack
Es una aplicación gráfica para buscar claves wifi.
.SH "AUTHOR"
qaircrack was written by Juan Roldan Ruiz <juan@shoden.es>
.PP
This manual page was written by Juan Roldan Ruiz <juan@shoden.es,
for the Debian project (and may be used by others).
